from __future__ import annotations
from typing import Protocol
from models.base import ModelEvent, ModelObserver


class BaseView(ModelObserver, Protocol):
    """
    모든 View 가 구현해야 하는 인터페이스.
    - ModelObserver 를 상속해 Model 이벤트를 직접 수신할 수 있다.
    - show_menu / get_menu_choice / show_error 는 Controller 가 호출하는 공통 계약.
    """
    def show_menu(self) -> None: ...
    def get_menu_choice(self) -> str: ...
    def get_title_input(self) -> str: ...
    def get_id_input(self, action: str) -> str: ...
    def show_error(self, message: str) -> None: ...
    def show_invalid_input(self) -> None: ...
    def show_exit(self) -> None: ...
    def on_model_changed(self, event: ModelEvent) -> None: ...
